### PR TITLE
Updates jitsi-lgpl-dependencies to 0ca42f1f00.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by bickelj** [comment]
libjitsi build fails for me, can't find this jar:

Downloading: https://github.com/jitsi/jitsi-maven-repository/raw/master/snapshots/org/jitsi/jitsi-lgpl-dependencies/1.1-SNAPSHOT/jitsi-lgpl-dependencies-1.1-20180407.162923-3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.436 s
[INFO] Finished at: 2018-04-08T17:33:07-05:00
[INFO] Final Memory: 20M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project libjitsi: Could not resolve dependencies for project org.jitsi:libjitsi:bundle:9001.9-custom: Could not find artifact org.jitsi:jitsi-lgpl-dependencies:jar:1.1-20180407.162923-3 in jitsi-maven-repository-snapshots (https://github.com/jitsi/jitsi-maven-repository/raw/master/snapshots/) -> [Help 1]

**Comment by bickelj** [comment]
Able to work around by cloning the jitsi-lgpl-dependencies repo and marking it with a custom version as well from 0ca42f1...

**Comment by damencho** [comment]
@bickelj Sorry it is my fault. It should be fine now.

**Comment by bickelj** [comment]
Works great now, thanks!

**Pull request merged**
