### PR TITLE
feat: Disable RTCP termination for 1:1 calls.

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Comment by bbaldino** [comment]
what's the win like for doing this?

**Comment by gpolitis** [comment]
The sender adapts to the end-to-end link, and not the sender-bridge link.

**Comment by bbaldino** [comment]
seems like that wouldn't be very valuable unless we disabled simulcast, too--are we doing that?

**Comment by gpolitis** [comment]
That would be the right thing to do, but we cannot easily disable simulcast and then re-enable it because of this Chrome bug https://bugs.chromium.org/p/webrtc/issues/detail?id=7555.

**Comment by bbaldino** [comment]
but if we can't disable simulcast, does disabling rtcp termination help much?

**Comment by gpolitis** [comment]
why wouldn't it help? if the receiver is sitting on a poor link, what's the benefit of the sender sending at high bitrate?

**Comment by bbaldino** [comment]
but won't it already just use the existing logic to forward a lower simulcast layer?  i guess this allows for more granular bitrate changes than jumping layers, i was just wondering if the new code paths introduced were worth the tradeoff.

**Comment by gpolitis** [comment]
I lost you. Could you please help me understand your question?

**Comment by gpolitis** [comment]
Actually this won't work at all because of adaptivity and bandwidth probing.

**Pull request closed without merging**
