### PR TITLE
Tries to fix the ptime attribute for opus.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by ibauersachs** [comment]
Does that fix jitsi/jitsi#266?

**Comment by ibauersachs** [comment]
I'm not an SDP specialist, but if the old output was:
```
a=fmtp:96 usedtx=1
a=ptime:96 20
```
then with this patch, the new output would be `a=fmtp:96 usedtx=1; ptime=20`. But RFC7587 says they must be like this if present:
```
a=fmtp:96 usedtx=1
a=ptime:20
a=maxptime:40
```

Am I missing something?

**Comment by bgrozev** [comment]
You are right, Ingo. I didn't look at the spec, and naively thought the format is the one that is obvious and makes sense.

**Comment by ibauersachs** [comment]
RFC != makes sense :(

**Pull request closed without merging**
