### PR TITLE
Allow user to specify RSA key generation parameters via configuration.

### PR DESCRIPTION
**Pull request by bickelj**
Adds two configuration options:
    org.jitsi.impl.neomedia.transform.dtls.RSA_KEY_SIZE
and
    org.jitsi.impl.neomedia.transform.dtls.RSA_KEY_SIZE_CERTAINTY

The first is the size in bits of the RSA key to be presented by libjitsi on a DTLS handshake.
The second is the certainty passed to BigNumber constructor.

Either may be set by java system properties (e.g. -D) or by the jitsi configuration service (sip-communicator.properties).

A sample on a jitsi-videobridge server updating the key size to 3072 bit RSA keys:
```$ cat ~/.sip-communicator/sip-communicator.properties
org.jitsi.impl.neomedia.transform.dtls.RSA_KEY_SIZE_CERTAINTY=80
org.jitsi.impl.neomedia.transform.dtls.RSA_KEY_SIZE=3072```

Defaults of 1024 and 80, respectively, remain the same as before. Some minor refactoring to move the numbers out of the method doing the generation.

### CODE REVIEW

**Comment by mondain** [comment]
While I don't need this yet in my project, I would like to see it get added to the lib. Also nice job on the patch.

**Comment by ibauersachs** [comment]
@bickelj can you please rebase this and fix the conflicts?

**Comment by bickelj** [comment]
@ibauersachs I would gladly create a new PR based on the new code and link to it from this one, if that would be acceptable to you (considering what happened last rebase).

It may be several days before I get a chance to do it.

**Comment by ibauersachs** [comment]
I'm sorry this got left behind, we've all been too busy and probably have forgotten about it too.

**Comment by bickelj** [comment]
This PR is obsoleted by https://github.com/jitsi/libjitsi/pull/134
Therefore closing.

**Pull request closed without merging**
