### PR TITLE
adds convertMsTo24Bits to RTPUtils

### PR DESCRIPTION
**Pull request by jcchuks**
moves `convertMsTo24Bits` method from RemoteBitrateEstimatorAbsSendTime to RTPUtils.java

### CODE REVIEW

**Comment by bgrozev** [comment]
In general, I don't mind moving this method to the utils class. However:
1. The method still exists in RemoteBitrateEstimatorAbsSendTime
2. It is not used anywhere. I see that you use it in TransportCCEngine in your branch, but I this is incorrect -- we shouldn't be saving the RTP timestamps of outgoing packets, but the time at which the packets we actually send.

**Comment by jcchuks** [comment]
I removed the method in my last commit on RBEAbsSendTime.

> It is not used anywhere. I see that you use it in TransportCCEngine in your branch, but I this is incorrect -- we shouldn't be saving the RTP timestamps of outgoing packets, but the time at which the packets we actually send.

Okay, makes sense. I thought about using `System.currentTimeToMillis()` in place of the RTP timestamp, but it doesn't look like it too.  My thought is that this timestamp should be obtained using `System.currentTimeToMillis()` somewhere after the bandwidth controller has scheduled and sent the packet. Please how do I retrieve the correct timestamp?

**Comment by bgrozev** [comment]
There aren't any components on the bridge that would delay a packet. Some might drop packets, or make some modifications, but that's OK for your use. The local system time saved at the time the packet passed through the transport-cc engine should work.

**Comment by jcchuks** [comment]
Okay, nice 


Sent from Yahoo Mail for iPhone


On Wednesday, August 16, 2017, 11:30 AM, bgrozev <notifications@github.com> wrote:


There aren't any components on the bridge that would delay a packet. Some might drop packets, or make some modifications, but that's OK for your use. The local system time saved at the time the packet passed through the transport-cc engine should work.

**Comment by gpolitis** [comment]
Superseded by #361.

**Pull request closed without merging**
