### PR TITLE
Initial documentation of ConfigurationService parameters added

### PR DESCRIPTION
**Pull request by zbettenbuk**
Created a list of all sip-communicator.properties (or System) variables that libjitsi uses at the moment.

### CODE REVIEW

**Comment by mondain** [comment]
This is a nice guide, missing from the repo; my two cents.

**Comment by zbettenbuk** [comment]
Don't we need this PR, can I close it?

**Comment by mondain** [comment]
Why would you guys not merge this? This is a decent doc.

**Comment by ibauersachs** [comment]
Ideally I'd want to get such a file automatically generated, but in the meantime I'm fine adding this. @zbettenbuk Please sign the [CLA](https://jitsi.org/icla) if you haven't already done so.

**Comment by zbettenbuk** [comment]
@ibauersachs: thanks, i think i'm covered by the LogMeIn group agreement

**Pull request merged**
