### PR TITLE
Support "message" media type.

### PR DESCRIPTION
**Pull request by tuijldert**
A trivial change to also support a "message" media description.

### CODE REVIEW

**Comment by bgrozev** [comment]
I don't know if this is safe or not (we iterate over the media types in many places). Please reopen if you still need it.

**Comment by tuijldert** [comment]
It is needed if/when Jitsi wants to support MSRP (which was initiated by Jitsi to begin with).
It'd be needed when merging https://github.com/jitsi/jitsi/pull/3.

As for it being 'safe', that's what testing is for, no?

**Comment by tuijldert** [comment]
You'd have that already ever since 2013, I believe.

Cheers,
Tom.

**Comment by bgrozev** [comment]
@tuijldert sorry for the confusion here. I am not planning on merging this now, but just FYI in case you have other contributions: we have a new CLA (since last year); it can be signed online ([induvidual](https://jitsi.org/icla), or [corporate](https://jitsi.org/ccla))

**Comment by tuijldert** [comment]
Sorry, this 1 kind of fell through the cracks…

Anyway, you should have a newly signed document by now.

 

Hope this helps,

Tom.

**Comment by ibauersachs** [comment]
Jenkins, test this please.

**Comment by ibauersachs** [comment]
@bgrozev I've looked through the iterations in libjitsi and it seems safe enough to merge it there. Jenkins agrees. Anything in particular you're afraid of breaking?

**Comment by bgrozev** [comment]
No, nothing in particular.

**Pull request merged**
