### PR TITLE
Also cache certificate and fingerprint in DtlsControlImpl

### PR DESCRIPTION
**Pull request by champtar**
No reasons to compute a new cert with the same keypair

Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

### CODE REVIEW

**Comment by bgrozev** [comment]
Jenkins: add to whitelist

**Comment by champtar** [comment]
@ibauersachs do you want me to also remove the leading '_'

**Comment by ibauersachs** [comment]
Yes.

**Comment by lyubomir** [comment]
@champtar & @ibauersachs, I have my own version in my local clone. May I please take over the merge of this PR?

**Comment by champtar** [comment]
You can close this one if you think yours is better.

**Comment by champtar** [comment]
@lyubomir i've updated the commit to remove '_'
can you merge your patch or mine?

**Pull request merged**
