### PR TITLE
Refactors Logger. Adds a second Logger implementation with more flexible

### PR DESCRIPTION
**Pull request by bgrozev**
level configuration.

### CODE REVIEW

**Comment by ibauersachs** [comment]
Please hold off with merging this, I'm a bit concerned about the package org.jitsi.util and making Logger abstract.

**Comment by bgrozev** [comment]
Jenkins: test this please

**Comment by bgrozev** [comment]
@ibauersachs , I'll hold.

**Comment by bgrozev** [comment]
@ibauersachs FYI: I tested Jitsi after replacing the ice4j and libjitsi jars, and didn't notice any problems.

**Comment by ibauersachs** [comment]
Do we know of any other libjitsi users that could be affected (i.e. outside of jitsi-x)?

And then there's the issue about org.jitsi.util... There are already multiple libraries (can't remember if there's more than the lgpl-deps) declaring this package and thus breaking OSGi. Moving more classes here doesn't help unless libjitsi is declared the master library for org.jitsi.util and the others get migrated at some point.

Otherwise: LGTM

**Comment by bgrozev** [comment]
> Do we know of any other libjitsi users that could be affected (i.e. outside of jitsi-x)?

Unless I am missing something, this shouldn't affect users: the Logger constructor used to be private, and the Logger.getLogger(Class<?>) and Logger.getLogger(String) APIs are unchanged.

The ice4j change may break compilation because its new Logger class clashes with java.util.logging.Logger, but that's an easy fix.

> And then there's the issue about org.jitsi.util... There are already multiple libraries (can't remember if there's more than the lgpl-deps) declaring this package and thus breaking OSGi. Moving more classes here doesn't help unless libjitsi is declared the master library for org.jitsi.util and the others get migrated at some point.

I couldn't find org.jitsi.util in other places apart from lgpl-deps. As far as I know, libjitsi is the right place for these classes (there was some duplication with net.sip.communicator.util, but that's a separate package). If we need to add another util package in another repository, we should then make sure to use another package name (like org.jitsi.jicofo.util does).

**Comment by ibauersachs** [comment]
> Unless I am missing something, this shouldn't affect users: the Logger constructor used to be private, and the Logger.getLogger(Class<?>) and Logger.getLogger(String) APIs are unchanged.

Right, I missed the private constructor.

> The ice4j change may break compilation because its new Logger class clashes with java.util.logging.Logger, but that's an easy fix.

The wildcard imports are a (bad) Jitsi practice, discouraged, and rarely used by other projects. Anyway, this is a compile-time only issue.

**Comment by damencho** [comment]
Jenkins: test this please

**Comment by damencho** [comment]
Jenkins: test this please

**Pull request merged**
