### PR TITLE
Corrected documentation on MediaServiceImpl

### PR DESCRIPTION
**Pull request by jcchuks**
Corrected the explanation of the boolean fields; net.java.sip.communicator.service.media.DISABLE\_AUDIO\_SUPPORT  and net.java.sip.communicator.service.media.DISABLE\_VIDEO\_SUPPORT

### CODE REVIEW

**Comment by jcchuks** [comment]
Thanks, I have signed the documentation. I am hoping to participate on the project under GSoC.

**Comment by bgrozev** [comment]
Hey @jcchuks 

Thank you for the contribution! We may need a few days to confirm the CLA on our end (it requires human work), but we'll add you to the jenkins list so that it doesn't complain any more.

About the specific changes: looking at the code (MediaServiceImpl.java), the default value for these properties is "false", and since the properties have "DISABLE" in their name, the default behavior is to enable the detection of audio/video devices. So it looks to me like the original documentation is correct. Does that make sense, or am I missing something?

Jenkins, add to whitelist.

**Comment by jcchuks** [comment]
Thanks @bgrozev , 

What you said makes sense since default value is "false". I have just corrected the sentence _"the detection of the audio CaptureDevices is disabled"_ to  _"the detection of the audio CaptureDevices is enabled"_ in my fork.

I feel it reads better as  "_**the detection of the audio CaptureDevices is enabled**_" in the docs than "_the audio CaptureDevices are detected._".  Same for video.  

If the emboldened statement is sound (please correct me if am wrong), then I would ask that this pull request be closed, then I can make another pull request with the corrected version. 

Thanks.

**Comment by bgrozev** [comment]
LGTM

**Comment by bgrozev** [comment]
Got the CLA. Thanks again for the contribution.

**Comment by jcchuks** [comment]
My pleasure. Thanks.

**Pull request merged**
