### PR TITLE
Update boncycastle from 1.51 to 1.54

### PR DESCRIPTION
**Pull request by champtar**
This is the same version as in jitsi-universe, just setting it in the stone as I want to update to 1.54

### CODE REVIEW

**Comment by mondain** [comment]
I'm using BC 1.53 and it seems to work just fine; my 2 cents.

**Comment by gpolitis** [comment]
We're actually building bouncycastle from this branch https://github.com/gpolitis/bc-java because it contains a fix required for Firefox support. So, in order to switch to 1.53 we need to merge the changes from upstream into the aforementioned branch, build the library and push to our GH maven repository.

**Comment by gpolitis** [comment]
Actually @damencho just brought to my attention that DTLS version negotiation is supposed to be fixed in BouncyCastle 1.4. We need to test this new version against the bridge, and eventually switch to that if no other problem arises.

**Comment by champtar** [comment]
I ve a patch to fix the build failure, i ll sens et tomorrow (it's on my work PC)

**Comment by champtar** [comment]
Here is my patch. I'm using bouncy castle 1.54 in all jitsi's projects and i can join a room with firefox nightly (is it a good enough test?)

**Comment by bickelj** [comment]
Just tested bc 1.54 in:
libjitsi
jitsi-videobridge (using above libjitsi)
jicofo (using above libjitsi)

These three on the jitsi-meet server, Abrowser 43.0.4 (Firefox) Trisquel GNU/Linux had successful video chat with Firefox 43.0.4 on another operating system.

Tests with jitsi client to jitsi client over videobridge were unsuccessful but that may have been due to other factors.

**Comment by ibauersachs** [comment]
@gpolitis Any reason not to merge this?

**Comment by gpolitis** [comment]
If we merge this, libjitsi will depend on 1.54 and jitsi-videobridge and jicofo on 1.51-jitsi-1. Since 1.54 has fixed DTLS negotiation, I don't see a reason why not to use 1.54 everywhere but maybe I'm missing something?

**Comment by champtar** [comment]
Maybe we should update bc in jitsi-universe

**Pull request merged**
