### PR TITLE
Sets a capacity of 100 to the LinkedBlockingQueue-s used to hold obje…

### PR DESCRIPTION
**Pull request by bgrozev**
…cts to be reused.

### CODE REVIEW

**Comment by mondain** [comment]
Might I suggest that you make the value a parameter using the Config service?

**Comment by bgrozev** [comment]
Is this a general suggestion, or you see a case where you would need to tune it?

**Comment by mondain** [comment]
I'd like the option to tune something that is set to create ~400 extra objects * number of streams I've got going.

**Comment by bgrozev** [comment]
It will not create 400 objects for each stream, it will limit the number of these objects to 100 per queue. Until now there was practically no limit.

**Comment by mondain** [comment]
It's true that what you've done is probably better than leaving it open-ended and possibly leading to an OOM error and while it doesn't create ~400 objects, it creates slots for them to be inserted per stream. If allowing the implementer some means to configure this is not applicable, at least you've shown me a spot extend these classes.

**Comment by bgrozev** [comment]
I still don't see how this would be a useful control to have, and I don't have time to spend on it. If you'd like to implement it I would be happy to review and merge, though.

**Comment by ibauersachs** [comment]
@bgrozev Can you please rebase this PR against current master? 900769c5a6967676e0054401a6b6dc2f5a47b448 introduced incompatible changes.

**Comment by bgrozev** [comment]
Rebased. Also included Paul's suggestion.

**Pull request merged**
