### PR TITLE
Adds statistics per ssrc in MediaStreamStats and their implementation.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by damencho** [comment]
Jenkins: ok to test again.

**Comment by damencho** [comment]
Jenkins: ok to test again.

**Comment by brianh5** [comment]
any plan to get this in soon?

**Comment by jitsi-developers** [comment]
Hi Team,

We are looking for an open source SDK/API for integrating desktop, Web,
Android and IOS devices to simulate/develop a Skype type application using
which users can chat, send video/audio and documents as attachment, share
screen etc.

The client has there own encryption algorithm which they want to integrate
with the open source SDK.

Is it possible to use your APIs and achieve the above described solution?
Please send me the details on an urgent basis so that we can take a
decision and suggest the same to our client and implement it for them.

Regards,

[image: photo]
*Pankaj Kumar*
Chief Technology Officer, Mobiloitte Technologies (I) Pvt. Ltd.
+919810099044 | +919810602676 | www.mobiloitte.com | Skype: mobiloitte_316
<#> | A-235, Okhla Phase-I, New Delhi - 110020

**Pull request merged**
