### PR TITLE
Jenkins KO test

### PR DESCRIPTION
**Pull request by champtar**
Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>

### CODE REVIEW

**Comment by ibauersachs** [comment]
What is that?

**Comment by champtar** [comment]
just to test that jenkins is KO again

**Comment by champtar** [comment]
Or to be more precise that some bad code has been merged that make tests fail for everyone

**Comment by lyubomir** [comment]
I'll close this PR because I tested a PR multiple times today and the tests seemed to work fine for me.

**Pull request closed without merging**
